# Generated by Django 6.0 on 2026-01-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('obj', 'Objective'), ('essay', 'Essay')], max_length=20)),
                ('expected_answer', models.TextField()),
                ('max_score', models.FloatField(default=1.0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Exam.exam')),
            ],
            options={
                'indexes': [models.Index(fields=['exam', 'question_type'], name='Question_qu_exam_id_a8bac8_idx')],
            },
        ),
    ]
